#!/bin/bash
echo 'hello world'
# Create a folder to store the downloaded files
mkdir -p OverwatchIcons

# Download each file using curl
curl -o OverwatchIcons/Icon-Tracer.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/29/Icon-Tracer.png/revision/latest/scale-to-width-down/75?cb=20221005170620" 
curl -o OverwatchIcons/Icon-Reaper.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a9/Icon-Reaper.png/revision/latest/scale-to-width-down/75?cb=20221005170219" 
curl -o OverwatchIcons/Icon-Widowmaker.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/54/Icon-Widowmaker.png/revision/latest/scale-to-width-down/75?cb=20221005170629" 
curl -o OverwatchIcons/Icon-Pharah.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/29/Icon-Pharah.png/revision/latest/scale-to-width-down/75?cb=2022100517021" 
curl -o OverwatchIcons/Icon-Reinhardt.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/83/Icon-Reinhardt.png/revision/latest/scale-to-width-down/75?cb=20221005161659" 
curl -o OverwatchIcons/Icon-Mercy.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/03/Icon-Mercy.png/revision/latest/scale-to-width-down/75?cb=20221005160926" 
curl -o OverwatchIcons/Icon-Torbjörn.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ca/Icon-Torbj%C3%B6rn.png/revision/latest/scale-to-width-down/75?cb=2022100517061" 
curl -o OverwatchIcons/Icon-Hanzo.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/71/Icon-Hanzo.png/revision/latest/scale-to-width-down/75?cb=20221005165925" 
curl -o OverwatchIcons/Icon-Winston.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/f8/Icon-Winston.png/revision/latest/scale-to-width-down/75?cb=2022100516172" 
curl -o OverwatchIcons/Icon-Zenyatta.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/f7/Icon-Zenyatta.png/revision/latest/scale-to-width-down/75?cb=20221005160943" 
curl -o OverwatchIcons/Icon-Bastion.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/51/Icon-Bastion.png/revision/latest/scale-to-width-down/75?cb=20221005165909" 
curl -o OverwatchIcons/Icon-Symmetra.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/06/Icon-Symmetra.png/revision/latest/scale-to-width-down/75?cb=20221005170604" 
curl -o OverwatchIcons/Icon-Zarya.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/75/Icon-Zarya.png/revision/latest/scale-to-width-down/75?cb=20221005161732" 
curl -o OverwatchIcons/Icon-cassidy.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/5b/Icon-cassidy.png/revision/latest/scale-to-width-down/75?cb=20221006034952" 
curl -o OverwatchIcons/Icon-Soldier76.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/10/Icon-Soldier76.png/revision/latest/scale-to-width-down/75?cb=202210051702376" 
curl -o OverwatchIcons/Icon-Lúcio.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/51/Icon-L%C3%BAcio.png/revision/latest/scale-to-width-down/75?cb=20221004204914" 
curl -o OverwatchIcons/Icon-Roadhog.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/16/Icon-Roadhog.png/revision/latest/scale-to-width-down/75?cb=20221005161706" 
curl -o OverwatchIcons/Icon-Junkrat.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/99/Icon-Junkrat.png/revision/latest/scale-to-width-down/75?cb=2022100517020Junkrat" 
curl -o OverwatchIcons/Icon-D.Va.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/19/Icon-D.Va.png/revision/latest/scale-to-width-down/75?cb=20221005161600" 
curl -o OverwatchIcons/Icon-Mei.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/99/Icon-Mei.png/revision/latest/scale-to-width-down/75?cb=20221005170206" 
curl -o OverwatchIcons/Icon-Genji.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1c/Icon-Genji.png/revision/latest/scale-to-width-down/75?cb=2022100516593" 
curl -o OverwatchIcons/Icon-Ana.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/3d/Icon-Ana.png/revision/latest/scale-to-width-down/75?cb=20221005160847" 
curl -o OverwatchIcons/Icon-Sombra.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/70/Icon-Sombra.png/revision/latest/scale-to-width-down/75?cb=20221005170556" 
curl -o OverwatchIcons/Icon-Orisa.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/11/Icon-Orisa.png/revision/latest/scale-to-width-down/75?cb=20221005161652" 
curl -o OverwatchIcons/Icon-Doomfist.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a1/Icon-Doomfist.png/revision/latest/scale-to-width-down/75?cb=20221005161638" 
curl -o OverwatchIcons/Icon-Moira.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/55/Icon-Moira.png/revision/latest/scale-to-width-down/75?cb=20221005160935" 
curl -o OverwatchIcons/Icon-Brigitte.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a6/Icon-Brigitte.png/revision/latest/scale-to-width-down/75?cb=20221005160917" 
curl -o OverwatchIcons/Icon-Wrecking_Ball.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ca/Icon-Wrecking_Ball.png/revision/latest/scale-to-width-down/75?cb=20221005161727" 
curl -o OverwatchIcons/Icon-ashe.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/84/Icon-ashe.png/revision/latest/scale-to-width-down/75?cb=20221006035040" 
curl -o OverwatchIcons/Icon-Baptiste.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/fb/Icon-Baptiste.png/revision/latest/scale-to-width-down/75?cb=20221005160910" 
curl -o OverwatchIcons/Icon-Sigma.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/e/e0/Icon-Sigma.png/revision/latest/scale-to-width-down/75?cb=20221005161714" 
curl -o OverwatchIcons/Icon-Echo.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d6/Icon-Echo.png/revision/latest/scale-to-width-down/75?cb=20221005165920" 
curl -o OverwatchIcons/Icon-Sojourn.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/e/e0/Icon-Sojourn.png/revision/latest/scale-to-width-down/75?cb=20221005170226" 
curl -o OverwatchIcons/Icon-Junker_Queen.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/2b/Icon-Junker_Queen.png/revision/latest/scale-to-width-down/75?cb=20221005161646" 
curl -o OverwatchIcons/Icon-kiriko.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ca/Icon-kiriko.png/revision/latest/scale-to-width-down/75?cb=20221004202610" 
curl -o OverwatchIcons/Icon-Ramattra.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/6f/Icon-Ramattra.png/revision/latest/scale-to-width-down/75?cb=20221206190323" 
curl -o OverwatchIcons/Icon-Lifeweaver.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/86/Icon-Lifeweaver.png/revision/latest/scale-to-width-down/75?cb=2023041118132" 
curl -o OverwatchIcons/Icon-Illari.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/86/Icon-Illari.png/revision/latest/scale-to-width-down/75?cb=20230811015354" 
curl -o OverwatchIcons/Icon-Mauga.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/39/Icon-Mauga.png/revision/latest/scale-to-width-down/75?cb=20231205235708"
curl -o OverwatchIcons/Icon-Venture.png "https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a0/Icon-Venture.png/revision/latest/scale-to-width-down/65?cb=20240417102123"

echo "All files downloaded successfully!"